//! Parity harness — compares Rust scanner output against Python reference metadata.
//!
//! Fixtures are generated by `fixtures/generate_fixtures.py`.
//! The `reference_metadata.json` contains the Python `extract_metadata` output
//! for each fixture. This test runs the Rust scanner on the same files and
//! asserts field-by-field parity.

use aurora_core::scanner::extract_metadata;
use std::path::Path;

/// Path to the fixtures directory relative to the crate root.
fn fixtures_dir() -> &'static Path {
    Path::new("tests/fixtures")
}

/// Load the Python reference metadata from JSON.
fn load_reference() -> serde_json::Value {
    let path = fixtures_dir().join("reference_metadata.json");
    let data = std::fs::read_to_string(&path).expect("Failed to read reference_metadata.json");
    serde_json::from_str(&data).expect("Failed to parse reference_metadata.json")
}

#[test]
fn test_parity_mp3() {
    let path = fixtures_dir().join("test_song.mp3");
    let meta = extract_metadata(path.to_str().unwrap())
        .expect("Rust scanner returned None for MP3");
    let ref_data = load_reference();
    let py = &ref_data["test_song.mp3"];

    assert_eq!(meta.title, py["title"].as_str().unwrap(), "title mismatch");
    assert_eq!(meta.artist, py["artist"].as_str().unwrap(), "artist mismatch");
    assert_eq!(meta.album.as_deref(), py["album"].as_str(), "album mismatch");
    assert_eq!(meta.file_format, py["file_format"].as_str().unwrap(), "format mismatch");

    // Artists list
    let py_artists: Vec<String> = py["artists"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap().to_string())
        .collect();
    assert_eq!(meta.artists, py_artists, "artists mismatch");

    // Duration (allow ±1 second rounding)
    let py_dur = py["duration"].as_i64().unwrap();
    assert!(
        (meta.duration.unwrap() - py_dur).abs() <= 1,
        "duration mismatch: Rust={}, Python={}",
        meta.duration.unwrap(),
        py_dur
    );

    // ReplayGain
    let rg_track = meta.replaygain_track_gain.unwrap();
    let py_rg = py["replaygain_track_gain"].as_f64().unwrap();
    assert!(
        (rg_track - py_rg).abs() < 0.01,
        "RG track_gain mismatch: Rust={}, Python={}",
        rg_track,
        py_rg
    );

    let rg_peak = meta.replaygain_track_peak.unwrap();
    let py_peak = py["replaygain_track_peak"].as_f64().unwrap();
    assert!(
        (rg_peak - py_peak).abs() < 0.01,
        "RG track_peak mismatch: Rust={}, Python={}",
        rg_peak,
        py_peak
    );

    // Album art — driven by Python reference
    let py_has_art = py["has_album_art"].as_bool().unwrap();
    assert_eq!(
        meta.album_art_bytes.is_some(),
        py_has_art,
        "MP3 art parity mismatch: Rust={}, Python={}",
        meta.album_art_bytes.is_some(),
        py_has_art
    );
}

#[test]
fn test_parity_flac() {
    let path = fixtures_dir().join("test_song.flac");
    let meta = extract_metadata(path.to_str().unwrap())
        .expect("Rust scanner returned None for FLAC");
    let ref_data = load_reference();
    let py = &ref_data["test_song.flac"];

    assert_eq!(meta.title, py["title"].as_str().unwrap());
    assert_eq!(meta.artist, py["artist"].as_str().unwrap());
    assert_eq!(meta.album.as_deref(), py["album"].as_str());
    assert_eq!(meta.file_format, "flac");

    // Multi-value artist: FLAC should produce ["Artist A", "Artist B"]
    let py_artists: Vec<String> = py["artists"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap().to_string())
        .collect();
    assert_eq!(meta.artists, py_artists, "FLAC multi-artist mismatch");

    // ReplayGain
    let rg = meta.replaygain_track_gain.unwrap();
    let py_rg = py["replaygain_track_gain"].as_f64().unwrap();
    assert!((rg - py_rg).abs() < 0.01);

    // Album art — driven by Python reference
    let py_has_art = py["has_album_art"].as_bool().unwrap();
    assert_eq!(
        meta.album_art_bytes.is_some(),
        py_has_art,
        "FLAC art parity mismatch"
    );
}

#[test]
fn test_parity_ogg() {
    let path = fixtures_dir().join("test_song.ogg");
    let meta = extract_metadata(path.to_str().unwrap())
        .expect("Rust scanner returned None for OGG");
    let ref_data = load_reference();
    let py = &ref_data["test_song.ogg"];

    assert_eq!(meta.title, py["title"].as_str().unwrap());
    assert_eq!(meta.artist, py["artist"].as_str().unwrap());
    assert_eq!(meta.album.as_deref(), py["album"].as_str());
    assert_eq!(meta.file_format, "ogg");

    // Featured artists: "OGG Artist feat. Guest" → primary="OGG Artist", featured=["Guest"]
    let py_artists: Vec<String> = py["artists"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap().to_string())
        .collect();
    assert_eq!(meta.artists, py_artists, "OGG artists mismatch");

    let py_featured: Vec<String> = py["featured_artists"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap().to_string())
        .collect();
    assert_eq!(
        meta.featured_artists.as_ref().unwrap(),
        &py_featured,
        "OGG featured mismatch"
    );

    // ReplayGain
    let rg = meta.replaygain_track_gain.unwrap();
    let py_rg = py["replaygain_track_gain"].as_f64().unwrap();
    assert!((rg - py_rg).abs() < 0.01);

    // Album art (OGG metadata_block_picture) — driven by Python reference
    let py_has_art = py["has_album_art"].as_bool().unwrap();
    assert_eq!(
        meta.album_art_bytes.is_some(),
        py_has_art,
        "OGG art parity mismatch: Rust={}, Python={}",
        meta.album_art_bytes.is_some(),
        py_has_art
    );
}

#[test]
fn test_parity_m4a() {
    let path = fixtures_dir().join("test_song.m4a");
    let meta = extract_metadata(path.to_str().unwrap())
        .expect("Rust scanner returned None for M4A");
    let ref_data = load_reference();
    let py = &ref_data["test_song.m4a"];

    assert_eq!(meta.title, py["title"].as_str().unwrap());
    assert_eq!(meta.artist, py["artist"].as_str().unwrap());
    assert_eq!(meta.album.as_deref(), py["album"].as_str());
    assert_eq!(meta.file_format, "m4a_aac", "M4A should be detected as AAC");

    // Album art — driven by Python reference
    let py_has_art = py["has_album_art"].as_bool().unwrap();
    assert_eq!(
        meta.album_art_bytes.is_some(),
        py_has_art,
        "M4A art parity mismatch"
    );
}

#[test]
fn test_unreadable_file_returns_none() {
    let result = extract_metadata("/nonexistent/path/fake.mp3");
    assert!(result.is_none(), "Unreadable file should return None, not panic");
}

#[test]
fn test_format_tier_values() {
    use aurora_core::scanner::format_tier;

    assert_eq!(format_tier("flac"), 6);
    assert_eq!(format_tier("wav"), 5);
    assert_eq!(format_tier("m4a_alac"), 4);
    assert_eq!(format_tier("ogg"), 3);
    assert_eq!(format_tier("opus"), 3);
    assert_eq!(format_tier("m4a_aac"), 2);
    assert_eq!(format_tier("m4a"), 2);
    assert_eq!(format_tier("mp3"), 1);
    assert_eq!(format_tier("aac"), 1);
    assert_eq!(format_tier("wma"), 1);
    assert_eq!(format_tier("aiff"), 1);
    assert_eq!(format_tier("ape"), 1);
    assert_eq!(format_tier("wv"), 1);
    assert_eq!(format_tier("xyz"), 0);
}
